config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"

  get 'free_cell/play'
  get 'free_cell/play/:id', to: 'free_cell#play'
  get 'free_cell/create'
  post 'free_cell/create'
  get 'free_cell/cancel'
  get 'free_cell/history'
  get 'free_cell/stats'

  get 'access/options'
  post 'access/options'

  get 'access/register'
  post 'access/register'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'


  get '/purge', to: 'welcome#purge'
  get '/help', to: 'free_cell#help'

  mount ActionCable.server => "/cable"
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_logged_in, :except => [:login, :register, :attempt_login, :logout]

  def options
    @unlock_golden_wins = 3

    @totals = {}
    @totals["singleplayer_wins"] = 0
    @totals["singleplayer_losses"] = 0
    @totals["time-attack_wins"] = 0
    @totals["time-attack_losses"] = 0

    @matches = Match.where("end_time IS NOT NULL AND (player1=? OR player2=?)", @user.id.to_i, @user.id.to_i).order(end_time: :desc)

    @matches.each do |m|
      if m.player_winner == @user.id
        @totals[m.game_mode + "_wins"] += 1
      else
        @totals[m.game_mode + "_losses"] += 1
      end
    end

    # if you submitted the options form
    if params[:options].present?
      volume = params[:options][:volume]
      skin = params[:options][:skin]

      if skin == "golden" and @totals["singleplayer_wins"] < @unlock_golden_wins
        skin = "normal"
      end

      @user.volume = volume
      @user.card_skin = skin
      @user.save
      flash.now[:notice] = "Your settings have been adjusted to your specifications, good sir."
    end
  end

  def login
    # display login form
  end

  def register
    # if you have submitted the register form
    #
    if params[:username].present? && params[:password].present?
      username = params[:username]
      password = params[:password]

      check_user = User.where(:username => username).first

      if check_user
        flash.now[:notice] = "A user with this username already exists."
      else
        new_user = User.create(:username => username, :password => password)

        cookies.signed[:user_id] = new_user.id

        if params[:password].size < 5
          flash[:notice] = "That's a shitty password, but whatever... Account created."
        else
          flash[:notice] = "Account created."
        end

        redirect_to(root_path)

      end

    end


  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first

      if found_user
        authorized_user = found_user.authenticate(params[:password])

      end
    end

    if authorized_user
      cookies.signed[:user_id] = authorized_user.id
      flash[:notice] = "You are now logged in."
      redirect_to(root_path)
    else
      flash.now[:notice] = "Invalid username/password combination"
      render('login')
    end
  end

  def logout
    cookies.signed[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to(access_login_path)

  end



  private

  def confirm_logged_in
    unless cookies.signed[:user_id]
      flash[:notice] = "Please login in."
      redirect_to(access_login_path)
    end
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<h2> Login to Freecell Faceoff </h2>

<div class="login">
  <%= form_tag(access_attempt_login_path, :method => :post) do %>
    <table>
      <tr>
        <td><%= label_tag(:username) %>:</td>
        <td><%= text_field_tag(:username, params[:username]) %></td>
      </tr>
      <tr>
        <td><%= label_tag(:password) %>:</td>
        <td><%= password_field_tag(:password) %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= submit_tag("Log In") %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/access/options.html.erb
<h2> Game Settings </h2>

<%= form_tag(access_options_path, :method => :post) do %>
  <b>Music Volume:</b><br>
  <%= range_field(:options, :volume, :in => 0..100, :step => 5, :value => @user.volume) %><br><br>

  <b>Skin:</b>
  <table style="margin:0;text-align:center;">
    <tr>
      <td style="width:120px;">
        <img src="/images/1.png">
      </td>
      <td style="width:120px;">
        <img src="/images/golden/1.png">
      </td>
    </tr>
    <tr>
      <td style="width:120px;">
        <%= radio_button_tag 'options[skin]', 'normal', @user.card_skin == 'normal' %>
      </td>
      <td style="width:120px;">
        <% if @totals["singleplayer_wins"] >= @unlock_golden_wins %>
          <%= radio_button_tag 'options[skin]', 'golden', @user.card_skin == 'golden' %>
        <% else %>
          <small><i>Unlock at <b><%= @unlock_golden_wins %></b> Singleplayer wins</i></small>
        <% end %>
      </td>
    </tr>
  </table><br>

  <%= submit_tag("Change") %>

<% end %>

app/views/access/register.html.erb
<h2> Register for Freecell Faceoff </h2>

<div class="register">
  <%= form_tag(access_register_path, :method => :post) do %>
    <table>
      <tr>
        <td><%= label_tag(:username) %>:</td>
        <td><%= text_field_tag(:username, params[:username]) %></td>
      </tr>
      <tr>
        <td><%= label_tag(:password) %>:</td>
        <td><%= password_field_tag(:password) %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= submit_tag("Register") %></td>
      </tr>
    </table>
  <% end %>
</div>

<div style="border:2px solid black;padding:5px;background-color:#EEc107ee;color:#111a;margin:25px;font-size:14px;">
  <h3 style="margin: 0">Registration Tips</h3>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Don't get attached to your account; this is a just a small easily hackable web game. I doubt I'll even bother adding score tracking.<br>
</div>