config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"

  get 'free_cell/play'
  get 'free_cell/play/:id', to: 'free_cell#play'
  get 'free_cell/create'
  post 'free_cell/create'
  get 'free_cell/cancel'
  get 'free_cell/history'
  get 'free_cell/stats'

  get 'access/options'
  post 'access/options'

  get 'access/register'
  post 'access/register'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'


  get '/purge', to: 'welcome#purge'
  get '/help', to: 'free_cell#help'

  mount ActionCable.server => "/cable"
end

app/controllers/free_cell_controller.rb
class FreeCellController < ApplicationController
  before_action :confirm_logged_in

  def play
    @params = params
    @user = User.find_by_id(cookies.signed[:user_id])

    if params[:id].present?
      @match = Match.find_by_id(params[:id])

      if @match.present?
        if @match.player1 == @user.id
          flash[:notice] = "You cannot join your own game"
          redirect_to :controller => 'welcome', :action => 'index'
        else
          @match.player2 = cookies.signed[:user_id]
          @match.save
        end
      end
    end
  end

  def create
    @params = params
    @user = User.find_by_id(cookies.signed[:user_id])

    if params[:game_mode]
      Match.create(@user.id, params[:game_mode])

      redirect_to :controller => 'free_cell', :action => 'play'
    end

  end

  def history

    @totals = {}
    @totals["singleplayer_wins"] = 0
    @totals["singleplayer_losses"] = 0
    @totals["time-attack_wins"] = 0
    @totals["time-attack_losses"] = 0

    @matches = Match.where("end_time IS NOT NULL AND (player1=? OR player2=?)", @user.id.to_i, @user.id.to_i).order(end_time: :desc)

    @matches.each do |m|
      if m.player_winner == @user.id
        @totals[m.game_mode + "_wins"] += 1
      else
        @totals[m.game_mode + "_losses"] += 1
      end
    end

    @matches = Match.where("end_time IS NOT NULL AND (player1=? OR player2=?)", @user.id.to_i, @user.id.to_i).order(end_time: :desc).limit(10)
  end

  def cancel
    # remove your match
    if @current_match.present?
      @current_match.delete
    end
    flash[:notice] = "You have forfeited your current match."
    redirect_to :controller => 'welcome', :action => 'index'
  end

  def stats
    @total_matches = Match.count
    @total_singleplayer = Match.where("game_mode=?", "singleplayer").count
    @total_timeattack = Match.where("game_mode=?", "time-attack").count
    @total_users = User.count

    @matches = Match.where("end_time IS NOT NULL").order(end_time: :desc).limit(10)
  end

  private

  def confirm_logged_in
    unless cookies.signed[:user_id]
      flash[:notice] = "Please login in."
      redirect_to(access_login_path)
    end
  end

end

app/helpers/free_cell_helper.rb
module FreeCellHelper
end

app/views/free_cell/create.html.erb
<h2>Single-player</h2>
<%= button_to 'Play Now!', free_cell_create_path, :class => 'big_play_button', params: {'game_mode' => 'singleplayer'} %><br>

<h2>Multi-player</h2>
<%= button_to 'Time Attack', free_cell_create_path, :class => 'big_play_button', params: {'game_mode' => 'time-attack'} %><br>

app/views/free_cell/help.html.erb
<h2> How to play FreeCell  </h2>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FreeCell is a variant of the classic Solitaire card game that uses the standard 52-card deck. The cards are dealt face-up into 8 cascades (columns of overlapping cards) with the bottom card available for play. The layout also consists of four "free" cells (top-left) and four foundation piles (top-right). The free cells are buffer slots that can store cards temporarily.<br><br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The exposed bottom card of each cascade can be either moved into an empty cell or onto another bottom card of value one higher and of the opposite color (e.g: 2 of hearts can be played onto a 3 of clubs.) Aces can be moved directly into the four foundation piles, one for each suit. Afterwards, cards of the matching suit can be placed on top of the aces in ascending order. The game is won once all 52 cards have been moved to the foundation piles.<br><br>

<h2> How to play FreeCell Faceoff </h2>


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FreeCell Faceoff has multiple game modes. You can play by yourself in <b>Single-player</b> mode just as in the traditional game, or you can put a twist on the game in  multiplayer faceoff game modes with an opponent.<br><br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Time Attack:</b> Both players are given the same table, but are playing on their own instance of that table. The winner is whoever finishes the fastest.<br><br>

app/views/free_cell/history.html.erb
<h2>Match History</h2>

<table class="lobby_table" cellspacing="0" style="width: 50%;">
  <tr>
    <th style="width: 50%;">Game Type</th>
    <th style="width: 50%;">Win / Loss Ratio</th>
  </tr>

  <tr>
    <td>&nbsp;&nbsp;<b>Single-player</b></td>
    <td>
      <%= @totals["singleplayer_wins"] %> / <%= @totals["singleplayer_losses"] %>
      <% if @totals["singleplayer_wins"] + @totals["singleplayer_losses"] > 0 %>
        (<%= (100 * (@totals["singleplayer_wins"].to_f/(@totals["singleplayer_wins"] + @totals["singleplayer_losses"]))).to_int %>%)
      <% else %>
        (0%)
      <% end %>
    </td>
  </tr>

  <tr>
    <td>&nbsp;&nbsp;<b>Time Attack</b></td>
    <td>
      <%= @totals["time-attack_wins"] %> / <%= @totals["time-attack_losses"] %>
      <% if @totals["time-attack_wins"] + @totals["time-attack_losses"] > 0 %>
        (<%= (100 * (@totals["time-attack_wins"].to_f/(@totals["time-attack_wins"] + @totals["time-attack_losses"]))).to_int %>%)
      <% else %>
        (0%)
      <% end %>
    </td>
  </tr>
</table><br>

<table class="lobby_table" cellspacing="0" style="width: 650px">
  <tr>
    <th style="width: 50%;">Game Type</th>
    <th style="width: 25%;">Info</th>
    <th style="width: 25%;">Results</th>
  </tr>

  <% if !@matches.any? %>
    <tr>
      <td colspan="3">&nbsp;&nbsp;&nbsp;&nbsp;There are no pending matches.</td>
    </tr>
  <% else %>
    <% @matches.each do |m| %>
      <%
        # "player1" is always you for display
        if m.player1 == @user.id
          player1 = User.find_by_id(m.player1)
          player2 = User.find_by_id(m.player2)
        else
          player2 = User.find_by_id(m.player1)
          player1 = User.find_by_id(m.player2)
        end
        game_data = JSON.parse(m.game_data)

        time_string = (m.end_time.to_f - m.start_time.to_f)

        if time_string > 3600
          time_string = "a while"
        else
          time_string = (time_string / 60).floor.to_s.rjust(2, "0") + ":" +
            (time_string % 60).floor.to_s.rjust(2, "0") + "." +
            ((time_string * 10) % 10).floor.to_s
        end

      %><tr>
        <td>
        &nbsp;&nbsp;Game #<%= m.id %> &mdash;
          <% if m.game_mode == 'singleplayer' %>
            Single-player
          <% elsif m.game_mode == 'time-attack' %>
            Time Attack
          <% end %><br>

          <% if m.game_mode == 'singleplayer' %>
            <!-- &nbsp;&nbsp;&nbsp;&nbsp;<%#= player1.username %><br>-->
          <% elsif m.game_mode == 'time-attack' %>
             &nbsp;&nbsp;&nbsp;&nbsp;vs. <%= player2.username %><br>
          <% end %>
        &nbsp;&nbsp;&nbsp;&nbsp;<%= m.end_time.in_time_zone("Central Time (US & Canada)").strftime("%-m/%-e/%y  %l:%M%P") %>
        </td>
        <td>
          Turns: <%= game_data["turn_number"] %><br>
          Score: 0
        </td>
        <td>
          <% if m.player_winner == @user.id %>
            <% if m.end_type == 'forfeit' %>
              <b>Won</b> &mdash; Resigned
            <% elsif m.end_type == 'played' %>
              <b>Won</b> in <%= time_string %>
            <% end %>
          <% else %>
            <% if m.end_type == 'forfeit' %>
              <b>Lost</b> &mdash; Resigned
            <% elsif m.end_type == 'played' %>
              <b>Lost</b> &mdash; Game Over
            <% end %>
          <% end %>
        </td>
      </tr>

    <% end %>
  <% end %>

</table><br>

<div style="width:100%; text-align:center;">
<i>Only shows your last 10 matches.</i></div><br>

app/views/free_cell/play.html.erb
<script>
  Howler.volume(
      <%= @user.volume %> / 200
  )

  var skin = "<%= @user.card_skin %>";
</script>

<div id="game_loading">
  <h2>Play <s>Now</s> Soon!</h2>

  Awaiting other player connection.....<br>
  <div id="wait_timer">00.<small>0</small></div><br>

  <%= link_to 'Cancel Game', free_cell_cancel_path %><br><br>
</div>

<div id="game_window">

  <div id="status_bar">
    <div style="position:relative;">
      <span style="position: absolute;  left: 5px;" id="button_sound_on">
        <a href="javascript:void(0)" onclick="App.game.enable_sound(); return false;" class="game-action">
          <%= image_tag('mute.png', :size => '22x22', :alt => 'audio', :class => 'flag_t') %> Music
        </a>
      </span>

      <span style="position: absolute; display: none; left: 5px;" id="button_sound_off">
        <a href="javascript:void(0)" onclick="App.game.disable_sound(); return false;" class="game-action">
          <%= image_tag('audio.png', :size => '22x22', :alt => 'audio', :class => 'flag_t') %> Music
        </a>
      </span>


      <span id="title"><%= @user.username %></span> <span style="float:right;"></span>


      <span style="position: absolute; right:0;">
        <a href="javascript:void(0)" onclick="App.game.send_forfeit(); return false;" class="game-action">
         <%= image_tag('flag.png', :size => '24x24', :alt => 'c lock', :class => 'flag_t') %> Resign
        </a>
      </span>
    </div>
  </div>

  <div id="game_info" style="height: auto;">
    <table style="width:95%;height:100%;padding:0; margin: 0 auto;">
      <tr>
        <td style="width:33%;text-align:left;font-size:14px;" valign="center">
          Turn: <span id="turn_number">0</span><br>
          Score: 0
        </td>
        <td style="width:33%;text-align:center;" valign="center">vs. <span class="opponent_name"></span></td>
        <td style="width:33%;text-align:right;font-size:14px;" valign="center">
          <div class="timer_area">
            <%= image_tag('clock.png', :size => '24x24', :alt => 'c lock', :class => 'clock_t') %>

            <span id="game_timer">00.<small>0</small></span>
          </div>
        </td>
      </tr>
    </table>
  </div>

  <div id="game_over_bar">
    <b>Game Over</b><br>

    <div class="dotted_separator"></div>

    <div class="hidden_text singleplayer_text">
      You ran out of moves.<br><br>
      <%= button_to "Play Again?", free_cell_create_path, :class => 'big_play_button', :method => :get %>
    </div>

    <div class="hidden_text time-attack_text">
      <span class="hidden_text forfeit_text">You resigned to <span class="opponent_name"></span> in FreeCell Faceoff.</span>
      <span class="hidden_text played_text"><span class="opponent_name"></span> defeated you in FreeCell Faceoff.</span><br>

      <%= button_to "Play Again?", free_cell_create_path, :class => 'big_play_button', :method => :get %>
    </div>
  </div>

  <div id="game_won_bar">
    <b>Game Won</b><br>

    <div class="dotted_separator"></div>

    <div class="hidden_text singleplayer_text">
      You achieved FreeCell!<br><br>
      <%= button_to "Play Again?", free_cell_create_path, :class => 'big_play_button', :method => :get %>
    </div>

    <div class="hidden_text time-attack_text">
      <span class="hidden_text forfeit_text"><span class="opponent_name"></span> resigned to you in FreeCell Faceoff.</span>
      <span class="hidden_text played_text">You defeated <span class="opponent_name"></span> in FreeCell Faceoff.</span><br>

      <%= button_to "Play Again?", free_cell_create_path, :class => 'big_play_button', :method => :get %>
    </div>
  </div>

  <div id="disconnected_bar">
    <b>You have been disconnected!</b>
  </div>

  <div id="table">
    <div id="free0" class="free" location="freecell"></div>
    <div id="free1" class="free" location="freecell"></div>
    <div id="free2" class="free" location="freecell"></div>
    <div id="free3" class="free" location="freecell"></div>

    <div id="suit3" class="suit" location="foundation"></div>
    <div id="suit2" class="suit" location="foundation"></div>
    <div id="suit1" class="suit" location="foundation"></div>
    <div id="suit0" class="suit" location="foundation"></div>

    <div id="col0" class="column" location="column"></div>
    <div id="col1" class="column" location="column"></div>
    <div id="col2" class="column" location="column"></div>
    <div id="col3" class="column" location="column"></div>
    <div id="col4" class="column" location="column"></div>
    <div id="col5" class="column" location="column"></div>
    <div id="col6" class="column" location="column"></div>
    <div id="col7" class="column" location="column"></div>
  </div>
</div>

app/views/free_cell/stats.html.erb
<h2> Database Stats </h2>

<b>Total Matches:</b> <%= @total_matches %><br>
<b>Total Singleplayer:</b> <%= @total_singleplayer %><br>
<b>Total Multiplayer:</b> <%= @total_timeattack %><br>
<b>Total Users:</b> <%= @total_users %><br><br>

<h2> Recent Server Matches </h2>

<table class="lobby_table" cellspacing="0" style="width: 650px">
  <tr>
    <th style="width: 50%;">Game Type</th>
    <th style="width: 25%;">Info</th>
    <th style="width: 25%;">Results</th>
  </tr>

  <% if !@matches.any? %>
    <tr>
      <td colspan="3">&nbsp;&nbsp;&nbsp;&nbsp;There is no match history.</td>
    </tr>
  <% else %>
    <% @matches.each do |m| %>
      <%

        player1 = User.find_by_id(m.player1)
        player2 = User.find_by_id(m.player2)

        game_data = JSON.parse(m.game_data)

        time_string = (m.end_time.to_f - m.start_time.to_f)

        if time_string > 3600
          time_string = "a while"
        else
          time_string = (time_string / 60).floor.to_s.rjust(2, "0") + ":" +
            (time_string % 60).floor.to_s.rjust(2, "0") + "." +
            ((time_string * 10) % 10).floor.to_s
        end

      %><tr>
        <td>
        &nbsp;&nbsp;Game #<%= m.id %> &mdash;
          <% if m.game_mode == 'singleplayer' %>
            Single-player
          <% elsif m.game_mode == 'time-attack' %>
            Time Attack
          <% end %><br>

          <% if m.game_mode == 'singleplayer' %>
             &nbsp;&nbsp;&nbsp;&nbsp;<%= player1.username %><br>
          <% elsif m.game_mode == 'time-attack' %>
             &nbsp;&nbsp;&nbsp;&nbsp;<%= player1.username %> vs. <%= player2.username %><br>
          <% end %>
        &nbsp;&nbsp;&nbsp;&nbsp;<%= m.end_time.in_time_zone("Central Time (US & Canada)").strftime("%-m/%-e/%y  %l:%M%P") %>
        </td>
        <td>
          Turns: <%= game_data["turn_number"] %><br>
          Score: 0
        </td>
        <td>
          <% if m.player_winner == @user.id %>
            <% if m.end_type == 'forfeit' %>
              <b>Won</b> &mdash; Resigned
            <% elsif m.end_type == 'played' %>
              <b>Won</b> in <%= time_string %>
            <% end %>
          <% else %>
            <% if m.end_type == 'forfeit' %>
              <b>Lost</b> &mdash; Resigned
            <% elsif m.end_type == 'played' %>
              <b>Lost</b> &mdash; Game Over
            <% end %>
          <% end %>
        </td>
      </tr>

    <% end %>
  <% end %>

</table><br>